In [64]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\loges\z\lib\site-packages (8.0.32)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in c:\users\loges\z\lib\site-packages (from mysql-connector-python) (3.20.3)

WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)

In [143]:
import pandas as pd
import mysql.connector as sql
import streamlit as st
import plotly.express as px
import os
import json
from PIL import Image
import sqlite3

In [62]:
Logesh1 = r"C:\Users\loges\Documents\data\aggregated\transaction\country\india\state/"
aggtransactionlist = os.listdir(Logesh1)

Data1 = {'State': [], 'Year': [], 'Quarter': [], 'Transaction_type': [], 'Transaction_count': [],
            'Transaction_amount': []}
for state in agg_trans_list:
    cur_state = Logesh1 + state + "/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year = cur_state + year + "/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            A = json.load(data)
            
            for i in A['data']['transactionData']:
                name = i['name']
                count = i['paymentInstruments'][0]['count']
                amount = i['paymentInstruments'][0]['amount']
                Data1['Transaction_type'].append(name)
                Data1['Transaction_count'].append(count)
                Data1['Transaction_amount'].append(amount)
                Data1['State'].append(state)
                Data1['Year'].append(year)
                Data1['Quarter'].append(int(file.strip('.json')))
                
aggregatedtransaction = pd.DataFrame(Data1)

In [63]:
aggregatedtransaction

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
3589,west-bengal,2022,4,Peer-to-peer payments,184380244,6.202222e+11
3590,west-bengal,2022,4,Merchant payments,171667404,1.408077e+11
3591,west-bengal,2022,4,Recharge & bill payments,48921147,2.602663e+10
3592,west-bengal,2022,4,Financial Services,268388,2.611229e+08
3593,west-bengal,2022,4,Others,610414,4.579379e+08

In [64]:
Logesh2 = r"C:\Users\loges\Documents\data\aggregated\user\country\india\state/"

aggregateduserlist = os.listdir(Logesh2)

Data2 = {'State': [], 'Year': [], 'Quarter': [], 'Brands': [], 'Count': [],
            'Percentage': []}
for state in agg_user_list:
    cur_state = Logesh2 + state + "/"
    agg_year_list = os.listdir(cur_state)
    
    for year in agg_year_list:
        cur_year = cur_state + year + "/"
        agg_file_list = os.listdir(cur_year)

        for file in agg_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            B = json.load(data)
            try:
                for i in B["data"]["usersByDevice"]:
                    brand_name = i["brand"]
                    counts = i["count"]
                    percents = i["percentage"]
                    Data2["Brands"].append(brand_name)
                    Data2["Count"].append(counts)
                    Data2["Percentage"].append(percents)
                    Data2["State"].append(state)
                    Data2["Year"].append(year)
                    Data2["Quarter"].append(int(file.strip('.json')))
            except:
                pass

Aggregateduser = pd.DataFrame(Data2)

In [65]:
Aggregateduser

                          State  Year  Quarter   Brands    Count  Percentage
0     andaman-&-nicobar-islands  2018        1   Xiaomi     1665    0.247033
1     andaman-&-nicobar-islands  2018        1  Samsung     1445    0.214392
2     andaman-&-nicobar-islands  2018        1     Vivo      982    0.145697
3     andaman-&-nicobar-islands  2018        1     Oppo      501    0.074332
4     andaman-&-nicobar-islands  2018        1  OnePlus      332    0.049258
...                         ...   ...      ...      ...      ...         ...
6727                west-bengal  2022        1   Lenovo   330017    0.015056
6728                west-bengal  2022        1  Infinix   284678    0.012987
6729                west-bengal  2022        1     Asus   280347    0.012790
6730                west-bengal  2022        1    Apple   277752    0.012671
6731                west-bengal  2022        1   Others  2196334    0.100199

[6732 rows x 6 columns]

In [66]:
Logesh3 = r"C:\Users\loges\Documents\data\map\transaction\hover\country\india\state/"

maptransationlist = os.listdir(Logesh3)

Data3 = {'State': [], 'Year': [], 'Quarter': [], 'District': [], 'Count': [],
            'Amount': []}

for state in map_trans_list:
    cur_state = Logesh3 + state + "/"
    map_year_list = os.listdir(cur_state)
    
    for year in map_year_list:
        cur_year = cur_state + year + "/"
        map_file_list = os.listdir(cur_year)
        
        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            C = json.load(data)
            
            for i in C["data"]["hoverDataList"]:
                district = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                Data3["District"].append(district)
                Data3["Count"].append(count)
                Data3["Amount"].append(amount)
                Data3['State'].append(state)
                Data3['Year'].append(year)
                Data3['Quarter'].append(int(file.strip('.json')))
                
maptransation = pd.DataFrame(Data3)

In [67]:
maptransation

,State,Year,Quarter,District,Count,Amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
14631,west-bengal,2022,4,nadia district,12690126,2.804568e+10
14632,west-bengal,2022,4,birbhum district,7617444,1.614650e+10
14633,west-bengal,2022,4,purba medinipur district,14484229,3.309949e+10
14634,west-bengal,2022,4,maldah district,12492746,2.721861e+10
14635,west-bengal,2022,4,darjiling district,8827502,1.801650e+10

In [68]:
Logesh4 = r"C:\Users\loges\Documents\data\map\user\hover\country\india\state/"

mapuserlist = os.listdir(Logesh4)

Data4 = {"State": [], "Year": [], "Quarter": [], "District": [],
            "RegisteredUser": [], "AppOpens": []}

for state in map_user_list:
    cur_state = Logesh4 + state + "/"
    map_year_list = os.listdir(cur_state)
    
    for year in map_year_list:
        cur_year = cur_state + year + "/"
        map_file_list = os.listdir(cur_year)
        
        for file in map_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            D = json.load(data)
            
            for i in D["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appOpens = i[1]['appOpens']
                Data4["District"].append(district)
                Data4["RegisteredUser"].append(registereduser)
                Data4["AppOpens"].append(appOpens)
                Data4['State'].append(state)
                Data4['Year'].append(year)
                Data4['Quarter'].append(int(file.strip('.json')))
                
mapuser = pd.DataFrame(Data4)

In [69]:
mapuser

,State,Year,Quarter,District,RegisteredUser,AppOpens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
14635,west-bengal,2022,4,nadia district,1359420,33853990
14636,west-bengal,2022,4,birbhum district,855236,20950662
14637,west-bengal,2022,4,purba medinipur district,1346908,38278506
14638,west-bengal,2022,4,maldah district,954892,29023743
14639,west-bengal,2022,4,darjiling district,564562,15982631

In [70]:
Logesh5 = r"C:\Users\loges\Documents\data\top\transaction\country\india\state/"

toptranstionlist = os.listdir(path5)
Data5 = {'State': [], 'Year': [], 'Quarter': [], 'Pincode': [], 'Transaction_count': [],
            'Transaction_amount': []}

for state in top_trans_list:
    cur_state = Logesh5 + state + "/"
    top_year_list = os.listdir(cur_state)
    
    for year in top_year_list:
        cur_year = cur_state + year + "/"
        top_file_list = os.listdir(cur_year)
        
        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            E = json.load(data)
            
            for i in E['data']['pincodes']:
                name = i['entityName']
                count = i['metric']['count']
                amount = i['metric']['amount']
                Data5['Pincode'].append(name)
                Data5['Transaction_count'].append(count)
                Data5['Transaction_amount'].append(amount)
                Data5['State'].append(state)
                Data5['Year'].append(year)
                Data5['Quarter'].append(int(file.strip('.json')))
toptransation = pd.DataFrame(Data5)

In [71]:
toptransation

,State,Year,Quarter,Pincode,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,744101,1622,2.769298e+06
1,andaman-&-nicobar-islands,2018,1,744103,1223,2.238042e+06
2,andaman-&-nicobar-islands,2018,1,744102,969,3.519060e+06
3,andaman-&-nicobar-islands,2018,1,744105,685,1.298561e+06
4,andaman-&-nicobar-islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
7134,west-bengal,2022,4,722101,2900058,5.748321e+09
7135,west-bengal,2022,4,700135,2471048,3.527457e+09
7136,west-bengal,2022,4,732101,2407008,5.052109e+09
7137,west-bengal,2022,4,700091,2348447,2.176640e+09
7138,west-bengal,2022,4,711101,1765314,4.048329e+09

In [72]:
Logesh6 = r"C:\Users\loges\Documents\data\top\user\country\india\state/"
topuserlist = os.listdir(path6)
Data6 = {'State': [], 'Year': [], 'Quarter': [], 'Pincode': [],
            'RegisteredUsers': []}

for state in top_user_list:
    cur_state = Logesh6 + state + "/"
    top_year_list = os.listdir(cur_state)
    
    for year in top_year_list:
        cur_year = cur_state + year + "/"
        top_file_list = os.listdir(cur_year)
        
        for file in top_file_list:
            cur_file = cur_year + file
            data = open(cur_file, 'r')
            F = json.load(data)
            
            for i in F['data']['pincodes']:
                name = i['name']
                registeredUsers = i['registeredUsers']
                Data6['Pincode'].append(name)
                Data6['RegisteredUsers'].append(registeredUsers)
                Data6['State'].append(state)
                Data6['Year'].append(year)
                Data6['Quarter'].append(int(file.strip('.json')))
topuser = pd.DataFrame(Data6)

In [73]:
topuser

                          State  Year  Quarter Pincode  RegisteredUsers
0     andaman-&-nicobar-islands  2018        1  744103             1608
1     andaman-&-nicobar-islands  2018        1  744101             1108
2     andaman-&-nicobar-islands  2018        1  744105             1075
3     andaman-&-nicobar-islands  2018        1  744102             1006
4     andaman-&-nicobar-islands  2018        1  744104              272
...                         ...   ...      ...     ...              ...
7135                west-bengal  2022        4  700015           108457
7136                west-bengal  2022        4  742304           105471
7137                west-bengal  2022        4  721101           105279
7138                west-bengal  2022        4  700091           102363
7139                west-bengal  2022        4  700150           101966

[7140 rows x 5 columns]

In [104]:
aggregatedtransaction.to_csv('aggregated_transaction.csv',index=False)
Aggregateduser.to_csv('aggregated_user.csv',index=False)
maptransation.to_csv('map_transation.csv',index=False)
mapuser.to_csv('map_user.csv',index=False)
toptransation.to_csv('top_transation.csv',index=False)
topuser.to_csv('top_user.csv',index=False)

In [96]:
mydb = sql.connect(host="localhost",
                   user="root",
                   password="Logesh@123456789",
                   database= "phonepe"
                  )
print(mydb)
mycursor = mydb.cursor(buffered=True)

AttributeError: 'str' object has no attribute 'connect'

In [97]:
mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

('information_schema',)
('mysql',)
('performance_schema',)
('phonepe',)
('practice',)
('sys',)

In [90]:
mycursor.execute("USE phonepe")

In [99]:
mycursor.execute("create table aggregated_transaction (State varchar(100), Year int, Quarter int, Transaction_type varchar(100), Transaction_count int, Transaction_amount double)")


for i,row in aggregatedtransaction.iterrows():
    sql = "INSERT INTO aggregated_transaction VALUES (%s,%s,%s,%s,%s,%s)"
    mycursor.execute(sql, tuple(row))
    mydb.commit()

In [100]:
mycursor.execute("create table aggregated_user (State varchar(100), Year int, Quarter int, Brands varchar(100), Count int, Percentage double)")

for i,row in Aggregateduser.iterrows():
    sql = "INSERT INTO aggregated_user VALUES (%s,%s,%s,%s,%s,%s)"
    mycursor.execute(sql, tuple(row))
    mydb.commit()

In [101]:
mycursor.execute("create table map_transation (State varchar(100), Year int, Quarter int, District varchar(100), Count int, Amount double)")

for i,row in maptransation.iterrows():
    sql = "INSERT INTO map_transation VALUES (%s,%s,%s,%s,%s,%s)"
    mycursor.execute(sql, tuple(row))
    mydb.commit()

In [103]:
mycursor.execute("create table map_user (State varchar(100), Year int, Quarter int, District varchar(100), Registered_user int, App_opens int)")

for i,row in mapuser.iterrows():
    sql = "INSERT INTO map_user VALUES (%s,%s,%s,%s,%s,%s)"
    mycursor.execute(sql, tuple(row))
    mydb.commit()

In [105]:
mycursor.execute("create table top_transation (State varchar(100), Year int, Quarter int, Pincode int, Transaction_count int, Transaction_amount double)")

for i,row in toptransation.iterrows():
    sql = "INSERT INTO top_transation VALUES (%s,%s,%s,%s,%s,%s)"
    mycursor.execute(sql, tuple(row))
    mydb.commit()

In [106]:
mycursor.execute("create table top_user (State varchar(100), Year int, Quarter int, Pincode int, Registered_users int)")

for i,row in topuser.iterrows():
    sql = "INSERT INTO top_user VALUES (%s,%s,%s,%s,%s)"
    mycursor.execute(sql, tuple(row))
    mydb.commit()

In [107]:
mycursor.execute("show tables")
mycursor.fetchall()

[('aggregated_transaction',),
 ('aggregated_user',),
 ('map_transation',),
 ('map_user',),
 ('top_transation',),
 ('top_user',)]

In [ ]:
!pip uninstall streamlit

In [41]:
!pip install plotly

Collecting plotly

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading plotly-5.14.1-py2.py3-none-any.whl (15.3 MB)
     ---------------------------------------- 15.3/15.3 MB 7.1 MB/s eta 0:00:00
Collecting tenacity>=6.2.0
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
Requirement already satisfied: packaging in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from plotly) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from packaging->plotly) (3.0.9)
Installing collected packages: tenacity, plotly
Successfully installed plotly-5.14.1 tenacity-8.2.2

In [72]:
!pip install streamlit-option-menu

Requirement already satisfied: streamlit-option-menu in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (0.3.2)
Requirement already satisfied: streamlit>=0.63 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit-option-menu) (1.20.0)
Requirement already satisfied: altair<5,>=3.2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (4.2.2)
Requirement already satisfied: blinker>=1.0.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (1.6)
Requirement already satisfied: cachetools>=4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (5.3.0)
Requirement already satisfied: click>=7.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (8.1.3)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (6.1.0)
Requirement already satisfied: numpy in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (1.24.2)
Requirement already satisfied: packaging>=14.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (21.3)
Requirement already satisfied: pandas<2,>=0.25 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (1.5.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (9.5.0)
Requirement already satisfied: protobuf<4,>=3.12 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (3.20.3)
Requirement already satisfied: pyarrow>=4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (11.0.0)
Requirement already satisfied: pympler>=0.9 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (1.0.1)
Requirement already satisfied: python-dateutil in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (2.8.2)
Requirement already satisfied: requests>=2.4 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (2.28.2)
Requirement already satisfied: rich>=10.11.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (13.3.3)
Requirement already satisfied: semver in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (3.0.0)
Requirement already satisfied: toml in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (0.10.2)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (4.5.0)
Requirement already satisfied: tzlocal>=1.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (4.3)
Requirement already satisfied: validators>=0.2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (0.20.0)
Requirement already satisfied: gitpython!=3.1.19 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (3.1.31)
Requirement already satisfied: pydeck>=0.1.dev5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (0.8.0)
Requirement already satisfied: tornado>=6.0.3 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (6.2)
Requirement already satisfied: watchdog in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit>=0.63->streamlit-option-menu) (3.0.0)
Requirement already satisfied: entrypoints in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-option-menu) (0.4)
Requirement already satisfied: jinja2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-option-menu) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-option-menu) (4.17.1)
Requirement already satisfied: toolz in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-option-menu) (0.12.0)
Requirement already satisfied: colorama in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from click>=7.0->streamlit>=0.63->streamlit-option-menu) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from gitpython!=3.1.19->streamlit>=0.63->streamlit-option-menu) (4.0.10)
Requirement already satisfied: zipp>=0.5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from importlib-metadata>=1.4->streamlit>=0.63->streamlit-option-menu) (3.15.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from packaging>=14.1->streamlit>=0.63->streamlit-option-menu) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from pandas<2,>=0.25->streamlit>=0.63->streamlit-option-menu) (2022.6)
Requirement already satisfied: six>=1.5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil->streamlit>=0.63->streamlit-option-menu) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-option-menu) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-option-menu) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-option-menu) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-option-menu) (2022.12.7)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from rich>=10.11.0->streamlit>=0.63->streamlit-option-menu) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from rich>=10.11.0->streamlit>=0.63->streamlit-option-menu) (2.13.0)
Requirement already satisfied: pytz-deprecation-shim in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from tzlocal>=1.1->streamlit>=0.63->streamlit-option-menu) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from tzlocal>=1.1->streamlit>=0.63->streamlit-option-menu) (2023.3)
Requirement already satisfied: decorator>=3.4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from validators>=0.2->streamlit>=0.63->streamlit-option-menu) (5.1.1)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19->streamlit>=0.63->streamlit-option-menu) (5.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from jinja2->altair<5,>=3.2.0->streamlit>=0.63->streamlit-option-menu) (2.1.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit>=0.63->streamlit-option-menu) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit>=0.63->streamlit-option-menu) (0.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit>=0.63->streamlit-option-menu) (0.1.2)

In [5]:
!pip install streamlit-lottie

Requirement already satisfied: streamlit-lottie in c:\users\loges\z\lib\site-packages (0.0.3)

WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)
WARNING: Ignoring invalid distribution -treamlit (c:\users\loges\z\lib\site-packages)

Requirement already satisfied: streamlit>=0.63 in c:\users\loges\z\lib\site-packages (from streamlit-lottie) (1.21.0)
Requirement already satisfied: rich>=10.11.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (13.3.3)
Requirement already satisfied: pympler>=0.9 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (1.0.1)
Requirement already satisfied: protobuf<4,>=3.12 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (3.20.3)
Requirement already satisfied: validators>=0.2 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (0.20.0)
Requirement already satisfied: toml in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (0.10.2)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (4.11.3)
Requirement already satisfied: click>=7.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (8.0.4)
Requirement already satisfied: packaging>=14.1 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (22.0)
Requirement already satisfied: cachetools>=4.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (5.3.0)
Requirement already satisfied: python-dateutil in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (2.8.2)
Requirement already satisfied: gitpython!=3.1.19 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (3.1.31)
Requirement already satisfied: pyarrow>=4.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (11.0.0)
Requirement already satisfied: blinker>=1.0.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (1.6)
Requirement already satisfied: tornado>=6.0.3 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (6.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (9.4.0)
Requirement already satisfied: numpy in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (1.23.5)
Requirement already satisfied: watchdog in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (2.1.6)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (4.4.0)
Requirement already satisfied: tzlocal>=1.1 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (4.3)
Requirement already satisfied: pandas<2,>=0.25 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (1.5.3)
Requirement already satisfied: altair<5,>=3.2.0 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (4.2.2)
Requirement already satisfied: pydeck>=0.1.dev5 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (0.8.0)
Requirement already satisfied: requests>=2.4 in c:\users\loges\z\lib\site-packages (from streamlit>=0.63->streamlit-lottie) (2.28.1)
Requirement already satisfied: jinja2 in c:\users\loges\z\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-lottie) (3.1.2)
Requirement already satisfied: entrypoints in c:\users\loges\z\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-lottie) (0.4)
Requirement already satisfied: toolz in c:\users\loges\z\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-lottie) (0.12.0)
Requirement already satisfied: jsonschema>=3.0 in c:\users\loges\z\lib\site-packages (from altair<5,>=3.2.0->streamlit>=0.63->streamlit-lottie) (4.17.3)
Requirement already satisfied: colorama in c:\users\loges\z\lib\site-packages (from click>=7.0->streamlit>=0.63->streamlit-lottie) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\loges\z\lib\site-packages (from gitpython!=3.1.19->streamlit>=0.63->streamlit-lottie) (4.0.10)
Requirement already satisfied: zipp>=0.5 in c:\users\loges\z\lib\site-packages (from importlib-metadata>=1.4->streamlit>=0.63->streamlit-lottie) (3.11.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\loges\z\lib\site-packages (from pandas<2,>=0.25->streamlit>=0.63->streamlit-lottie) (2022.7)
Requirement already satisfied: six>=1.5 in c:\users\loges\z\lib\site-packages (from python-dateutil->streamlit>=0.63->streamlit-lottie) (1.16.0)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\loges\z\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-lottie) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\loges\z\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-lottie) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\loges\z\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-lottie) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\loges\z\lib\site-packages (from requests>=2.4->streamlit>=0.63->streamlit-lottie) (3.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\loges\z\lib\site-packages (from rich>=10.11.0->streamlit>=0.63->streamlit-lottie) (2.14.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\loges\z\lib\site-packages (from rich>=10.11.0->streamlit>=0.63->streamlit-lottie) (2.2.0)
Requirement already satisfied: tzdata in c:\users\loges\z\lib\site-packages (from tzlocal>=1.1->streamlit>=0.63->streamlit-lottie) (2023.3)
Requirement already satisfied: pytz-deprecation-shim in c:\users\loges\z\lib\site-packages (from tzlocal>=1.1->streamlit>=0.63->streamlit-lottie) (0.1.0.post0)
Requirement already satisfied: decorator>=3.4.0 in c:\users\loges\z\lib\site-packages (from validators>=0.2->streamlit>=0.63->streamlit-lottie) (5.1.1)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\loges\z\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19->streamlit>=0.63->streamlit-lottie) (5.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\loges\z\lib\site-packages (from jinja2->altair<5,>=3.2.0->streamlit>=0.63->streamlit-lottie) (2.1.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\loges\z\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit>=0.63->streamlit-lottie) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\loges\z\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit>=0.63->streamlit-lottie) (22.1.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\loges\z\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit>=0.63->streamlit-lottie) (0.1.2)

In [145]:
pip install --upgrade streamlit

Requirement already satisfied: streamlit in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (1.20.0)
Collecting streamlit
  Using cached streamlit-1.21.0-py2.py3-none-any.whl (9.7 MB)
Requirement already satisfied: altair<5,>=3.2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.2.2)
Requirement already satisfied: blinker>=1.0.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.6)
Requirement already satisfied: cachetools>=4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (5.3.0)
Requirement already satisfied: click>=7.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.1.3)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: numpy in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.24.2)
Requirement already satisfied: packaging>=14.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (21.3)
Requirement already satisfied: pandas<2,>=0.25 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.5.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (9.5.0)
Requirement already satisfied: protobuf<4,>=3.12 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (11.0.0)
Requirement already satisfied: pympler>=0.9 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.0.1)
Requirement already satisfied: python-dateutil in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.8.2)
Requirement already satisfied: requests>=2.4 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.28.2)
Requirement already satisfied: rich>=10.11.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (13.3.3)
Requirement already satisfied: toml in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.5.0)
Requirement already satisfied: tzlocal>=1.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.3)
Requirement already satisfied: validators>=0.2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.20.0)
Requirement already satisfied: gitpython!=3.1.19 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.1.31)
Requirement already satisfied: pydeck>=0.1.dev5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado>=6.0.3 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.2)
Requirement already satisfied: watchdog in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.0.0)
Requirement already satisfied: entrypoints in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit) (4.17.1)
Requirement already satisfied: toolz in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from altair<5,>=3.2.0->streamlit) (0.12.0)
Requirement already satisfied: colorama in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from click>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from gitpython!=3.1.19->streamlit) (4.0.10)
Requirement already satisfied: zipp>=0.5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from importlib-metadata>=1.4->streamlit) (3.15.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from packaging>=14.1->streamlit) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from pandas<2,>=0.25->streamlit) (2022.6)
Requirement already satisfied: six>=1.5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil->streamlit) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.4->streamlit) (2022.12.7)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from rich>=10.11.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from rich>=10.11.0->streamlit) (2.13.0)
Requirement already satisfied: pytz-deprecation-shim in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from tzlocal>=1.1->streamlit) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from tzlocal>=1.1->streamlit) (2023.3)
Requirement already satisfied: decorator>=3.4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from validators>=0.2->streamlit) (5.1.1)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19->streamlit) (5.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from jinja2->altair<5,>=3.2.0->streamlit) (2.1.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit) (0.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\loges\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit) (0.1.2)
Installing collected packages: streamlit
  Attempting uninstall: streamlit
    Found existing installation: streamlit 1.20.0
    Uninstalling streamlit-1.20.0:
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\loges\\appdata\\local\\programs\\python\\python311\\scripts\\streamlit.exe'
Consider using the `--user` option or check the permissions.

In [81]:
import pandas as pd

state_codes = [('andaman-&-nicobar-islands','35','AN'),
               ('andhra-pradesh','37','AP'),
               ('arunachal-pradesh','12','ANP'),
               ('assam','18','AS'),
               ('bihar','19','BH'),
               ('chandigarh','20','CHA'),
               ('chhattisgarh','21','CHAN'),
               ('dadra-&-nagar-haveli-&-daman-&-diu','22','DA'),
               ('delhi','23','DEH'),
               ('goa','24','GO'),
               ('gujarat','25','GUJ'),
               ('haryana','26','HAR'),
               ('himachal-pradesh','26','IMA'),
               ('jammu-&-kashmir','26','JAM'),
               ('jharkhand','26','JHA'),
               ('karnataka','26','KAR'),
               ('kerala','26','KER'),
               ('ladakh','26','LAD'),
               ('lakshadweep','26','LAK'),
               ('madhya-pradesh','26','MAD'),
               ('maharashtra','26','MAH'),
               ('manipur','26','MAN'),
               ('meghalaya','26','MEG'),
               ('mizoram','26','MIZ'),
               ('nagaland','26','NAG'),
               ('odisha','26','ODI'),
               ('puducherry','26','PUD'),
               ('punjab','26','PUN'),
               ('rajasthan','26','RAJ'),
               ('sikkim','26','SIK'),
               ('tamil-nadu','26','TMD'),
               ('telangana','36','TEL'),
               ('tripura','16','TRI'),
               ('uttar-pradesh','9','UP'),
               ('uttarakhand','5','UT'),
               ('west-bengal','19','WB')]

df = pd.DataFrame(state_codes, columns=["State",'Total_Transactions', 'Total_amount'])
df.to_csv("state_codes.csv", index=False)

In [82]:
print(df.shape)

(36, 3)

In [63]:
mydb = sql.connect(host="localhost",
                   user="root",
                   password="Logesh@123456789",
                   database= "phonepe"
                  )
print(mydb)
mycursor = mydb.cursor(buffered=True)

mycursor.execute(f"select state, sum(count) as Total_Transactions, sum(amount) as Total_amount from map_transation where year = {Year} and quarter = {Quarter} group by state order by state")
df1 = pd.DataFrame(mycursor.fetchall(),columns= ['State', 'Total_Transactions', 'Total_amount'])
print(df1.shape)

NameError: name 'sql' is not defined

In [101]:
%%writefile phone.py

import pandas as pd
import mysql.connector as sql
import streamlit as st
import plotly.express as px
import os
import json
from PIL import Image
from git.repo.base import Repo
from streamlit_option_menu import option_menu
from streamlit_lottie import st_lottie
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry





st.set_page_config(
    page_title="Phonepe Plus ",
    page_icon=(":shark:"),
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get help': 'https://github.com/LogeshkumarTamilselvam',
        'Report a bug': "https://www.linkedin.com/in/logeshkumar-tamilselvam-7258aa269/",
        'About': "# This is a header. This app only for *education purpose* created by Logeshkumar Tamilselvam!"
    }
)


# Load the image file using an absolute path
image_path = 'C:/Users/loges/Phonepeimage.jpeg'
with open(image_path, 'rb') as f:
    image_bytes = f.read()

# Display the image
st.image(image_bytes, use_column_width=True)


st.sidebar.header(":skull: :violet[**Hi folks! Choose the option option what you want**]")


mydb = sql.connect(host="localhost",
                   user="root",
                   password="Logesh@123456789",
                   database= "phonepe"
                  )
print(mydb)
mycursor = mydb.cursor(buffered=True)

import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

selected = option_menu("Main Menu", ["Home","Top Data","Explore Data","About"], 
                icons=["archive","check-square-fill","bar-chart-line", "exclamation-circle"],
                menu_icon= "menu-button-wide",
                default_index=0,
                orientation = "horizontal",
                styles={"nav-link": {"font-size": "20px", "text-align": "left", "margin": "-2px", "--hover-color": "#6F36AD"},
                        "nav-link-selected": {"background-color": "#6F36AD"}})

if selected == "Home":
    with open("spotlight_1.jpg", 'rb') as f:
        image_bytes = f.read()

    with st.container():
        st.image(image_bytes, use_column_width=True)
        st.markdown("# :violet[PhonePe Plus - THE BEAT OF PROGRESS]👨‍💻")
        st.markdown("## :red[The site only for education purpose]⚠️")

    session = requests.Session()
    retry = Retry(
        total=3,
        backoff_factor=0.5,
        status_forcelist=[429, 500, 502, 503, 504],
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    lottie_url = "https://assets6.lottiefiles.com/packages/lf20_cmaqoazd.json"
    lottie_animation = session.get(lottie_url).json()

    lottie_width = 400
    lottie_height = 500

    column1, column2 = st.columns([1,1],gap = "small")
    
    
    with column1:
        st.write(" ")
        st.write(" ")
        st.markdown("### :violet[Description :] The Indian digital payments story has truly captured the world's imagination. From the largest towns to the remotest villages, there is a payments revolution being driven by the penetration of mobile phones and data.")
        st.markdown("### :violet[Source :] [Phonepe](https://phonepe.com/)")
    
    with column2:
        st_lottie(lottie_animation, speed=1, width=lottie_width, height=lottie_height, key="hello")
        
        
        
elif selected == "Top Data":
    st.markdown("## :violet[Data Collections]")
    Type = st.selectbox("*All India**", ("Transactions", "Users"))
    Year = st.slider("**Year**", min_value=2018, max_value=2022)
    Quarter = st.slider("Quarter", min_value=1, max_value=4)
    
    if st.selectbox("**Type**", ("Transactions", "Users")) == "Transactions":
        
        column1,column2 = st.columns([1,1],gap="small")
    
    with column1:
        st.markdown("### :violet[State]")
        mycursor.execute(f"select state, sum(Transaction_count) as Total_Transactions_Count, sum(Transaction_amount) as Total from aggregated_transaction where year = {Year} and quarter = {Quarter} group by state order by Total desc limit 10")
        df = pd.DataFrame(mycursor.fetchall(), columns=['State', 'Transactions_Count','Total_Amount'])
        fig = px.pie(df, values='Total_Amount',
                     names='State',
                     title='Top 10',
                     color_discrete_sequence=px.colors.sequential.Agsunset,
                     hover_data=['Transactions_Count'],
                     labels={'Transactions_Count':'Transactions_Count'})
        
        
        fig.update_traces(textposition='inside', textinfo='percent+label')
        st.plotly_chart(fig,use_container_width=True)
        
    with column2:
        st.markdown("### :violet[District]")
        mycursor.execute(f"select district , sum(Count) as Total_Count, sum(Amount) as Total from map_transation where year = {Year} and quarter = {Quarter} group by district order by Total desc limit 10")
        df = pd.DataFrame(mycursor.fetchall(), columns=['District', 'Transactions_Count','Total_Amount'])
        
        
        fig = px.pie(df, values='Total_Amount',
                     names='District',
                     title='Top 10',
                     color_discrete_sequence=px.colors.sequential.Agsunset,
                     hover_data=['Transactions_Count'],
                     labels={'Transactions_Count':'Transactions_Count'})

        fig.update_traces(textposition='inside', textinfo='percent+label')
        st.plotly_chart(fig,use_container_width=True)
        
    
# Top Charts - USERS          
    if st.selectbox("**Type**", ("Transactions", "Users")) == "Users":
        col1,col2,col3 =st.columns([2,2,2],gap="small")
    with col1:
        st.markdown("### :violet[Brands]")
        if Year == 2022 and Quarter in [2,3,4]:
            st.error('The Data are inbetween 2022', icon="🚨")
        else:
            mycursor.execute(f"select brands, sum(count) as Total_Count, avg(percentage)*100 as Avg_Percentage from aggregated_user where year = {Year} and quarter = {Quarter} group by brands order by Total_Count desc limit 10")
            df = pd.DataFrame(mycursor.fetchall(), columns=['Brand', 'Total_Users','Avg_Percentage'])
            fig = px.bar(df,
                         title='Top 10',
                         x="Total_Users",
                         y="Brand",
                         orientation='h',
                         color='Avg_Percentage',
                         color_continuous_scale=px.colors.sequential.Agsunset)
            st.plotly_chart(fig,use_container_width=True) 
            
    with col2:
        st.markdown("### :violet[State]")
        mycursor.execute(f"select state, sum(Registered_user) as Total_Users, sum(App_opens) as Total_Appopens from map_user where year = {Year} and quarter = {Quarter} group by state order by Total_Users desc limit 10")
        df = pd.DataFrame(mycursor.fetchall(), columns=['State', 'Total_Users','Total_Appopens'])
        fig = px.pie(df, values='Total_Users',
                     names='State',
                     title='Top 10',
                     color_discrete_sequence=px.colors.sequential.Agsunset,
                     hover_data=['Total_Appopens'],
                     labels={'Total_Appopens':'Total_Appopens'})
        fig.update_traces(textposition='inside', textinfo='percent+label')
        st.plotly_chart(fig,use_container_width=True)
    
    with col3:
        st.markdown("### :violet[District]")
        mycursor.execute(f"select district, sum(Registered_User) as Total_Users, sum(app_opens) as Total_Appopens from map_user where year = {Year} and quarter = {Quarter} group by district order by Total_Users desc limit 10")
        df = pd.DataFrame(mycursor.fetchall(), columns=['District', 'Total_Users','Total_Appopens'])
        df.Total_Users = df.Total_Users.astype(float)
        fig = px.bar(df,
                     title='Top 10',
                     x="Total_Users",
                     y="District",
                     orientation='h',
                     color='Total_Users',
                     color_continuous_scale=px.colors.sequential.Agsunset)
        
        
        st.plotly_chart(fig,use_container_width=True)
        
        
        
        


    # MENU 3 - EXPLORE DATA
elif selected == "Explore Data":
    

    state_codes = [('andaman-&-nicobar-islands','35','AN'),
               ('andhra-pradesh','37','AP'),
               ('arunachal-pradesh','12','ANP'),
               ('assam','18','AS'),
               ('bihar','19','BH'),
               ('chandigarh','20','CHA'),
               ('chhattisgarh','21','CHAN'),
               ('dadra-&-nagar-haveli-&-daman-&-diu','22','DA'),
               ('delhi','23','DEH'),
               ('goa','24','GO'),
               ('gujarat','25','GUJ'),
               ('haryana','26','HAR'),
               ('himachal-pradesh','26','IMA'),
               ('jammu-&-kashmir','26','JAM'),
               ('jharkhand','26','JHA'),
               ('karnataka','26','KAR'),
               ('kerala','26','KER'),
               ('ladakh','26','LAD'),
               ('lakshadweep','26','LAK'),
               ('madhya-pradesh','26','MAD'),
               ('maharashtra','26','MAH'),
               ('manipur','26','MAN'),
               ('meghalaya','26','MEG'),
               ('mizoram','26','MIZ'),
               ('nagaland','26','NAG'),
               ('odisha','26','ODI'),
               ('puducherry','26','PUD'),
               ('punjab','26','PUN'),
               ('rajasthan','26','RAJ'),
               ('sikkim','26','SIK'),
               ('tamil-nadu','26','TMD'),
               ('telangana','36','TEL'),
               ('tripura','16','TRI'),
               ('uttar-pradesh','9','UP'),
               ('uttarakhand','5','UT'),
               ('west-bengal','19','WB')]

df = pd.DataFrame(state_codes, columns=["State",'Total_Transactions', 'Total_amount'])
df.to_csv("state_codes.csv", index=False)

st.markdown("## :violet[Overall State Data - Transactions Amount]")
Year = st.slider("**Year**", min_value=2018, max_value=2022)
Quarter = st.slider("Quarter", min_value=1, max_value=4)
mycursor.execute(f"select state, sum(count) as Total_Transactions, sum(amount) as Total_amount from map_transation where year = {Year} and quarter = {Quarter} group by state order by state")
df1 = pd.DataFrame(mycursor.fetchall(),columns= ['State', 'Total_Transactions', 'Total_amount'])
df2 = pd.read_csv('state_codes.csv')
df1 = df1.sort_values('State')
df2 = df2.sort_values('State')
6+
df_merged = pd.merge(df1, df2, on='State')

fig = px.choropleth(df_merged, geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
                    featureidkey='properties.ST_NM',
                    locations='State',
                    color='Total_Transactions_x',
                    color_continuous_scale='sunset')


fig.update_geos(fitbounds="locations", visible=False)
st.plotly_chart(fig, use_container_width=True)

Overwriting phone.py